<?php
$forcedBillingAddressChange = Mage::getSingleton('checkout/session')->getData('ForcedBillingAddressChange');
if($forcedBillingAddressChange){
    Mage::getSingleton('checkout/session')->unsetData('ForcedBillingAddressChange');
}
?>
<?php if(Mage::getSingleton('customer/session')->isLoggedIn() && Mage::helper('epicor_comm')->getErpAccountInfo()->getAccountType() == 'B2B'): ?>

<div class="block block-progress opc-block-progress">
    <div class="block-title">
        <strong><span><?php echo $this->__('Your Checkout Progress') ?></span></strong>
    </div>
    <div class="block-content">
        <dl>
        <?php echo $this->getChildHtml('pre_billing'); ?>    
        <?php if ($this->getCheckout()->getStepData('billing', 'is_show')): ?>
            <div id="billing-progress-opcheckout">
                <?php if ($this->isStepComplete('billing')): ?>               
                    <dt class="complete">
                       <?php echo $this->__('Billing Address') ?> 
                       <?php  if(!$forcedBillingAddressChange): ?>
                        <span class="separator">|</span>
                        <a href="#billing" onclick="checkout.gotoSection('billing'); return false;"><?php echo $this->__('Change') ?></a>
                       <?php endif ?> 
                    </dt>
                    <dd class="complete">
                        <address><?php echo $this->getBilling()->format('html') ?></address>
                    </dd>
                <?php else: ?>
                    <dt>
                        <?php echo $this->__('Billing Address') ?>
                    </dt>
                <?php endif; ?>
                    </div>
        <?php endif; ?>
        <?php echo $this->getChildHtml('pre_shipping'); ?>
        <?php if ($this->getCheckout()->getStepData('shipping', 'is_show')): ?>
            <div id="shipping-progress-opcheckout">
        <?php if ($this->isStepComplete('shipping')): ?>
            <dt class="complete">
                <?php echo $this->__('Shipping Address') ?> <span class="separator">|</span>
                <a href="#payment" onclick="checkout.gotoSection('shipping');return false;"><?php echo $this->__('Change') ?></a>
            </dt>
            <dd class="complete">
                <address><?php echo $this->getShipping()->format('html') ?></address>
            </dd>
        <?php else: ?>
            <dt>
                <?php echo $this->__('Shipping Address') ?>
            </dt>
        <?php endif; ?>
            </div>
        <?php endif; ?>

<?php if ($this->getCheckout()->getStepData(Silk_Retailer_Model_Retailer::STEP_CODE, 'is_show')): ?>
                <div id="<?php echo Silk_Retailer_Model_Retailer::STEP_CODE ?>-progress-opcheckout">
                    <?php if ($this->isStepComplete(Silk_Retailer_Model_Retailer::STEP_CODE)): ?>
                        <dt class="complete">
                            <?php echo $this->__('Shipping Retailer') ?> <span class="separator">|</span>
                            <a href="#payment" onclick="checkout.gotoSection('shipping');return false;"><?php echo $this->__('Change') ?></a>
                        </dt>
                        <dd class="complete">
                            <address><?php echo $this->getShipping()->format('html') ?></address>
                        </dd>
                    <?php else: ?>
                        <dt>
                            <?php echo $this->__('Shipping Retailer') ?>
                        </dt>
                    <?php endif; ?>
                </div>
            <?php endif; ?>



        <?php echo $this->getChildHtml('pre_shipping_method'); ?>
        <?php if ($this->getCheckout()->getStepData('shipping_method', 'is_show')): ?>
            <div id="shipping_method-progress-opcheckout">
        <?php if ($this->isStepComplete('shipping_method')): ?>
            <dt class="complete">
                <?php echo $this->__('Shipping Method') ?> <span class="separator">|</span>
                <a href="#shipping_method" onclick="checkout.gotoSection('shipping_method'); return false;"><?php echo $this->__('Change') ?></a>
            </dt>
            <dd class="complete">
                <?php if ($this->getShippingMethod()): ?>
                    <?php echo $this->escapeHtml($this->getShippingDescription()) ?>

                    <?php $_excl = $this->getShippingPriceExclTax(); ?>
                    <?php $_incl = $this->getShippingPriceInclTax(); ?>
                    <?php if ($this->helper('tax')->displayShippingPriceIncludingTax()): ?>
                        <?php echo $_incl; ?>
                    <?php else: ?>
                        <?php echo $_excl; ?>
                    <?php endif; ?>
                    <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                        (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                    <?php endif; ?>

                <?php else: ?>
                    <?php echo $this->__('Shipping method has not been selected yet') ?>
                <?php endif; ?>
            </dd>
        <?php else: ?>
            <dt>
                <?php echo $this->__('Shipping Method') ?>
            </dt>
        <?php endif; ?>
            </div>
        <?php endif; ?>
        <?php echo $this->getChildHtml('pre_shipping_dates'); ?>
        <?php if ($this->getCheckout()->getStepData('shipping_dates', 'is_show')): ?>
            <div id="shipping_dates-progress-opcheckout">
        <?php if ($this->isStepComplete('shipping_dates')): ?>
            <dt class="complete">
                <?php echo $this->__('Shipping Dates') ?> <span class="separator">|</span>
                <a href="#shipping_dates" onclick="checkout.gotoSection('shipping_dates'); return false;"><?php echo $this->__('Change') ?></a>
            </dt>
            <dd class="complete">
                <?php if ($this->getQuote()->getRequiredDate() !== '0000-00-00'  && $this->getQuote()->getRequiredDate() !== '1970-01-01'): ?>
                    <?php echo $this->__('Selected Shipping Date :') ?>
                    <?php echo $this->escapeHtml($this->getQuote()->getRequiredDate()) ?>

                <?php else: ?>
                    <?php echo $this->__('Next Available Date') ?>
                <?php endif; ?>
            </dd>
        <?php else: ?>
            <dt>
                <?php echo $this->__('Shipping Dates') ?>
            </dt>
        <?php endif; ?>
            </div>
        <?php endif; ?>
        <?php echo $this->getChildHtml('pre_payment'); ?>
        <?php if ($this->getCheckout()->getStepData('payment', 'is_show')): ?>
            <div id="payment-progress-opcheckout">
        <?php if ($this->isStepComplete('payment')): ?>
            <dt class="complete">
                <?php echo $this->__('Payment Method') ?> <span class="separator">|</span>
                <a href="#payment" onclick="checkout.gotoSection('payment'); return false;"><?php echo $this->__('Change') ?></a>
            </dt>
            <dd class="complete">
                <?php echo $this->getPaymentHtml() ?>
            </dd>
        <?php else: ?>
            <dt>
                <?php echo $this->__('Payment Method') ?>
            </dt>
        <?php endif; ?>
            </div>
        <?php endif; ?>
        </dl>
    </div>
</div>


<?php else: ?>

<div class="block block-progress opc-block-progress<?php if (!$this->isCustomerLoggedIn()/* && !$this->getCheckout()->getStepData('billing', 'is_show')*/): ?> opc-block-progress-step-login<?php endif; ?>">
    <div class="block-title">
        <strong><span><?php echo $this->__('Your Checkout Progress') ?></span></strong>
    </div>
    <div class="block-content">
        <dl>
            <?php if ($this->getCheckout()->getStepData('billing', 'is_show')): ?>
            <div id="billing-progress-opcheckout">
                <?php echo $this->getChildHtml('billing.progress') ?>
            </div>
            <?php endif; ?>

            <?php if ($this->getCheckout()->getStepData('shipping', 'is_show')): ?>
            <div id="shipping-progress-opcheckout">
                <?php echo $this->getChildHtml('shipping.progress') ?>
            </div>
            <?php endif; ?>

            <?php if (false && $this->getCheckout()->getStepData('shipping_method', 'is_show')): ?>
            <div id="shipping_method-progress-opcheckout">
                <?php echo $this->getChildHtml('shippingmethod.progress') ?>
            </div>
            <?php endif; ?>

            <?php if (false && $this->getCheckout()->getStepData('payment', 'is_show')): ?>
            <div id="payment-progress-opcheckout">
                <?php echo $this->getChildHtml('payment.progress') ?>
            </div>
            <?php endif; ?>
        </dl>
    </div>
</div>

<?php endif; ?>
