<?php
/**
 * Blackbird ContentManager Module
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to contact@bird.eu so we can send you a copy immediately.
 *
 * @category	Blackbird
 * @package		Blackbird_ContentManager
 * @copyright	Copyright (c) 2014 Blackbird Content Manager (http://black.bird.eu)
 * @author		Blackbird Team
 * @license		http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @version		1.6.2
 */
?>
<?php
    $node = $this->getNode();
    $menu = $this->getMenu();
    $url = $menu->getUrl($node);
?>
<li class="menu-item level-<?php echo $node['level']; ?> <?php echo $node['classes']; ?>" id="menu-item-<?php echo $node['node_id']; ?>">
    <?php if($url):?><a href="<?php echo $url; ?>" <?php if($node['target'] == '_blank'): ?>target="_blank"<?php endif; ?>><?php endif; ?>
        <span><?php echo $this->__($node['label']); ?></span>
    <?php if($url):?></a><?php endif; ?>
    
    <?php if($node['children_count'] > 0): ?>
        <div class="children">
            <ul class="level-<?php echo $node['level']; ?>">
                <?php foreach($node['children'] as $child): ?>
                    <?php echo $menu->render($child); ?>
                <?php endforeach; ?>
            </ul>
        </div>
    <?php endif; ?>
</li>
