<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Autorelated
 * @version    2.5.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
$abstractBlock = $this->helper('awautorelated')->getAbstractProductBlock();
$collection = $this->getCollection();

if ($this->getPosition() == AW_Autorelated_Model_Source_Position::INSTEAD_NATIVE_RELATED_BLOCK) {

    $this->iterateBlock();

    if ($collection && $collection->getSize()) {
        $this->markAsShowed();
    } elseif ($this->showNativeBlock()) {
        echo $this->getParent()->getChildHtml('catalog-product-related');
    }
}
?>
<?php if ($collection && $collection->getSize()) : ?>
<?php $_columnCount = $this->getColumnCount(); ?>
<div class="block block-related aw-arp-block-<?php echo $this->getData('id') ?>">
    <h2><?php echo $this->htmlEscape($this->getData('name')) ?></h2>
    <div class="block-content">
        <ul class="products-grid products-grid--max-6-col" id="block-related">
        <?php foreach ($collection as $product) : ?>
            <li class="item">
                <a href="<?php echo $abstractBlock->getProductUrl($product) ?>" title="<?php echo $this->htmlEscape($product->getName()) ?>" class="product-image">
                    <img src="<?php echo $this->helper('catalog/image')->init($product, 'thumbnail')->resize(208) ?>" width="208" height="208" alt="<?php echo $this->escapeHtml($product->getName()) ?>" />
                </a>
                <h3 class="product-name"><a href="<?php echo $abstractBlock->getProductUrl($product) ?>" title="<?php echo $this->htmlEscape($product->getName()) ?>"><?php echo $this->htmlEscape($product->getName()) ?></a></h3>
            </li>
        <?php endforeach ?>
        </ol>
        <script type="text/javascript">decorateList('block-related', 'none-recursive')</script>
    </div>
</div>
<?php endif;?>