<?php
/**
 *  Epicor_Comm_Block_Adminhtml_Customer_Group_Edit_Erpinfo
 */

/* @var $this Epicor_Comm_Block_Adminhtml_Customer_Erpaccount_Edit_Tab_Address */
?>
<?php
$erpCustomer = $this->getErpCustomer();
$options = Mage::getModel('epicor_comm/config_source_yesnonulloption')->toOptionArray();
$customAddressAllowed = $erpCustomer->getCustomAddressAllowed();
?>
<div class="entry-edit" >
    <div class="entry-edit-head"><h4 class="icon-head head-customer-view"><?php echo Mage::helper('epicor_comm')->__('ERP Group Addresses') ?></h4></div>
    <fieldset class="erp_addresses">
        <table>
            <tr>
                <td>
                    <strong><?php echo $this->__('Default Shipping Address:') ?></strong>
                    <?php echo $this->renderAddress($erpCustomer->getDefaultDeliveryAddressCode()) ?>
                </td>
                <td>
                    <strong><?php echo $this->__('Default Billing Address:') ?></strong>
                    <?php echo $this->renderAddress($erpCustomer->getDefaultInvoiceAddressCode()) ?>
                </td>
            </tr>
            <?php
            $num = 1;
            foreach ($this->getOtherAddresses() as $address) :
                if ($num % 2 != 0) :
                    ?>
                    <tr>
    <?php endif; ?>
                    <td>
                        <strong><?php echo $this->__('Alternative Address:') ?></strong>
                    <?php echo $this->renderAddress(null, $address); ?>
                    </td>
                <?php if ($num % 2 == 0) : ?>
                    </tr>
                <?php
                endif;
                $num++;
            endforeach;
            ?>
        </table>
    </fieldset>
    <div class="entry-edit-head">
        <h4 class="icon-head head-customer-view"><?php echo Mage::helper('epicor_comm')->__('Custom Addresses Allowed') ?></h4>
    </div>
    <fieldset id="erp_custom_address_allowed">
            <label for="erp_custom_address_allowed"><?php echo $this->__('Can Contacts Create Addresses?') ?></label>
            <select name="custom_address_allowed" id="custom_address_allowed" class="select">
               <?php foreach ($options as $key => $value): ?>
               <option value="<?php echo $value['value'] ?>" <?php if($customAddressAllowed == $value['value']) : ?>selected="selected"<?php endif; ?>><?php echo $value['label'] ?></option>
               <?php endforeach; ?>
           </select>
    </fieldset>
    <?php echo $this->getChildHtml('erp-right-box') ?>
</div>
<style>
    .erp_addresses table{
        width:100%;
    }
    .erp_addresses td {
        width:50%;
        padding-bottom:20px;
    }
</style>
