<?php
/**
 * Catalog top layered navigation
 *
 * @var Wyomind_Layer_Block_Catalog_Layer_View $this
 */
?>
<?php if ($this->canShowBlock()): ?>
    <div class="wyomind-layer-top sidebar">
        <div class="block block-layered-nav">
            <?php if ($this->canShowOptions()): ?>
                <p class="block-title block-subtitle block-subtitle--filter"><?php echo $this->__('Filter') ?></p>
                <div>
                    <?php $_filters = $this->getFilters() ?>
                    <?php foreach ($_filters as $_filter): ?>
                        <?php if ($_filter->getItemsCount()): ?>
                            <div class="block-content toggle-content">
                                <dl id="narrow-by-list">
                                    <dt class="filter-title"><?php echo $this->__($_filter->getName()) ?></dt>
                                    <dd class="filter-content"><?php echo $_filter->getHtml() ?></dd>
                                </dl>
                            </div>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>