<?php
$_galleryId = $this->getData('gallery_id');
$_init = $this->initGalleryPage($_galleryId);
$_gallery = $this->getData('gallery_object');
$_media = $this->getData('gallery_images');
?>

<div class="gallery-wrapper text-center gallery-<?php echo $_gallery->getId() ?> <?php echo $_gallery->getGalleryClass(); ?>">

    <?php if($_gallery->getShowTitle()): ?>
        <h1 class="gallery-title"><?php echo $_gallery->getTitle(); ?></h1>
    <?php endif; ?>

    <?php if($_gallery->getDescription()): ?>
        <p class="gallery-description"><?php echo $_gallery->getDescription(); ?></p>
    <?php endif; ?>

    <div class="uneven-grid-images row">

        <?php if(!empty($_media)): ?>
            <?php foreach($_media as $image): ?>

                <div class="grid-item-wrapper" data-tag-ids="<?php echo (string) $image->getTagIds(); ?>">

                    <?php if($this->hasProductLink($image)): ?>

                    <a class="grid-item-link product" href="<?php echo $this->getImageLink($image, $_gallery)?>" data-reveal-id="productModal" data-reveal-ajax="true">

                        <?php elseif($this->hasLink($_gallery, $image)): ?>

                        <a class="grid-item-link" href="<?php echo $this->getImageLink($image, $_gallery) ?>">

                            <?php else: ?>

                            <a class="grid-item-link" href="#" data-featherlight="<?php echo Mage::helper('gallery/gallery_image')->init($_gallery, 'image', $image->getFile())->keepTransparency(true)->keepFrame(false)?>">

                                <?php endif; ?>

                                <img data-id="<?php echo $count; ?>" src="<?php echo Mage::helper('gallery/gallery_image')->init($_gallery, 'image', $image->getFile())->keepTransparency(true)->keepFrame(false)->resize(430)->setQuality(70)?>" class="grid-item" />

                            </a>

                </div>

                <?php endforeach; ?>
        <?php endif; ?>

        <p class="no-images-match <?php if($_media): ?>no-display<?php endif; ?>" id="noImagesMatch"><?php echo $this->__('There are no images matching your filters.') ?></p>

    </div>

    <?php if($_gallery->getGalleryHtml()): ?>
        <div class="gallery-html">
            <?php echo $_gallery->getGalleryHtml(); ?>
        </div>
    <?php endif; ?>

</div>