<?php
$_galleryId = $this->getData('gallery_id');
$_gallery = Mage::getModel('gallery/gallery')->load($_galleryId);
$_media = $_gallery->getMediaGalleryImages();
?>

<div class="gallery-wrapper text-center gallery-<?php echo $_gallery->getId() ?> <?php echo $_gallery->getGalleryClass(); ?>">

    <?php if($_gallery->getShowTitle()): ?>
        <h1 class="gallery-title"><?php echo $_gallery->getTitle(); ?></h1>
    <?php endif; ?>

    <?php if($_gallery->getDescription()): ?>
        <p class="gallery-description"><?php echo $_gallery->getDescription(); ?></p>
    <?php endif; ?>

    <?php foreach($_media as $image): ?>

        <?php if($this->hasLink($image)): ?>
            <a class="grid-item-link" href="<?php echo $this->getImageLink($image, $_gallery) ?>">
        <?php endif; ?>

        <img src="<?php echo Mage::helper('gallery/gallery_image')->init($_gallery, 'image', $image->getFile())->keepTransparency(true)->keepFrame(false)?>"/>

        <div class="text-overlay-content">
            <?php if ($label = $image->getLabel()): ?>
                <h3><?php echo $this->__($label) ?></h3>
            <?php endif; ?>
            <?php if ($description = $image->getDescription()): ?>
                <p><?php echo $this->__($description) ?></p>
            <?php endif; ?>
        </div>

        <?php if($this->hasLink($image)): ?>
            </a>
        <?php endif; ?>

    <?php endforeach; ?>

    <?php if($_gallery->getGalleryHtml()): ?>
        <div class="gallery-html">
            <?php echo $_gallery->getGalleryHtml(); ?>
        </div>
    <?php endif; ?>

</div>
