<?php
/**
 * @var $this Wyomind_Layer_Block_Catalog_Layer_Filter_Price
 * @var $this Wyomind_Layer_Block_Catalog_Layer_Filter_Decimal
 */
$_currency = $this->getCurrentCurrency();
$_min = $this->getMin();
$_max = $this->getMax();
$_values = $this->getValues();
$_priceFormat = $this->getJsPriceFormat();
$_priceInputsEnabled = $this->helper('layer')->isPriceInputsEnabled();
?>
<div class="layer-slider">
    <div class="price-slider">
        <div class="bg"></div>
        <div class="handle min"></div>
        <div class="span"></div>
        <div class="handle max"></div>
    </div>

    <div class="price-range a-center">
        <?php echo $_currency->formatPrecision($_values[0], 0) ?> - <?php echo $_currency->formatPrecision($_values[1], 0) ?>
        <?php if ($_priceInputsEnabled): ?>
            <div>
                <input type="text" class="input-text" placeholder="min">
                <input type="text" class="input-text" placeholder="max">
            </div>
        <?php endif; ?>
    </div>

    <div class="price-limit">
        <input class="request-var" type="hidden" value="<?php echo $this->getRequestVar() ?>">
        <input class="price-min" type="hidden" value="<?php echo $_min ?>">
        <input class="price-max" type="hidden" value="<?php echo $_max ?>">
        <input class="price-value-min" type="hidden" value="<?php echo $_values[0] ?>">
        <input class="price-value-max" type="hidden" value="<?php echo $_values[1] ?>">
        <div class="max"><?php echo $_currency->formatPrecision($_max, 0) ?></div>
        <div class="min"><?php echo $_currency->formatPrecision($_min, 0) ?></div>
    </div>
</div>