<?php
/**
 * @var $this Wyomind_Layer_Block_Catalog_Layer_Js
 */
?>
<div id="wyomind-layer-overlay" style="display:none;">
    <img id="wyomind-layer-loader" src="<?php echo $this->getSkinUrl('images/wyomind/layer/loader.gif') ?>" width="64" height="68">
</div>
<script type="text/javascript">
//<![CDATA[
var WyomindLayer = new WyomindLayer({
    enableAjax: <?php echo $this->getAjaxEnabled(); ?>,
    enableAutoScroll: <?php echo $this->getAutoScrollEnabled(); ?>,
    enableAjaxToolbar: <?php echo $this->getAjaxToolbarEnabled(); ?>,
    currentUrl: '<?php echo $this->helper('core/url')->getCurrentUrl() ?>',
    priceFormat: <?php echo $this->helper('core')->jsonEncode($this->getJsPriceFormat()) ?>,
    onUpdateComplete: function() {
        $$('.block-layered-nav dt').invoke('observe', 'click', function () {
            WyomindLayer.handlePriceSliders();
        });

        WyomindLayer.adaptHeight('.wyomind-layer-top .block-content');
        WyomindLayer.adaptHeight('.category-products .product-info');

        if (typeof WyomindAjaxCart != 'undefined' && WyomindAjaxCart) {
            WyomindAjaxCart.init();
        }
    }
});
// Adapt filter height
WyomindLayer.adaptHeight('.wyomind-layer-top .block-content');
//]]>
</script>