<?php
$_galleryId = $this->getData('gallery_id');
$_gallery = Mage::getModel('gallery/gallery')->load($_galleryId);
$_media = $_gallery->getMediaGalleryImages();
?>

<div class="gallery-wrapper text-center gallery-<?php echo $_gallery->getId() ?> <?php echo $_gallery->getGalleryClass(); ?>">

    <?php if($_gallery->getShowTitle()): ?>
        <h1 class="gallery-title"><?php echo $_gallery->getTitle(); ?></h1>
    <?php endif; ?>

    <?php if($_gallery->getDescription()): ?>
        <p class="gallery-description"><?php echo $_gallery->getDescription(); ?></p>
    <?php endif; ?>

    <div class="even-grid-images row" data-equalizer>

        <?php foreach($_media as $image): ?>
            <div class="grid-item-wrapper">

                <?php if($this->hasProductLink($image)): ?>

                    <a class="grid-item-link product" href="<?php echo $this->getImageLink($image, $_gallery)?>" data-reveal-id="productModal" data-reveal-ajax="true">

                <?php elseif($this->hasLink($image)): ?>

                    <a class="grid-item-link" href="<?php echo $this->getImageLink($image, $_gallery) ?>">

                <?php endif; ?>

                <img class="grid-item" src="<?php echo Mage::helper('gallery/gallery_image')->init($_gallery, 'image', $image->getFile())->constrainOnly(false)->keepAspectRatio(false)->keepTransparency(true)->keepFrame(false)->resize(500, 500)?>"/>

                <?php if($this->hasLink($image) || $this->hasProductLink($image)): ?>
                    </a>
                <?php endif; ?>

            </div>
        <?php endforeach; ?>

    </div>

    <?php if($_gallery->getGalleryHtml()): ?>
        <div class="gallery-html">
            <?php echo $_gallery->getGalleryHtml(); ?>
        </div>
    <?php endif; ?>

</div>

<script type="text/javascript">
    //<![CDATA[

        var grid = $j('.even-grid-images').imagesLoaded(function() {
            grid.masonry({
                itemSelector: '.grid-item-wrapper',
                percentPosition: true,
                gutter: 10
            });
        });

    //]>
</script>