<?php
/**
 * Blackbird ContentManager Module
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to contact@bird.eu so we can send you a copy immediately.
 *
 * @category	Blackbird
 * @package		Blackbird_ContentManager
 * @copyright	Copyright (c) 2014 Blackbird Content Manager (http://black.bird.eu)
 * @author		Blackbird Team
 * @license		http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @version		1.6.2
 */
?>
<?php
    $collection = $this->getAttributeValues();
?>
<div class="block block-ct-filter">
    <div class="block-title">
        <strong><span><?php echo $this->__($this->getLabel()); ?></span></strong>
    </div>
    <div class="block-content block-ct-filter-content">
        <ul>
            <?php
                foreach($collection as $value):
            ?>
            <li class="<?php echo ($this->getActiveState($value->value))?'item-active':''; ?>">
                <a href="<?php echo $this->getFilteredUrl(array($this->getAttributeToFilter() => $value->value)); ?>">
                    <?php echo $value->title; ?>
                </a>
            </li>
            <?php endforeach; ?>
            <?php if($this->getViewAll()): ?>
                <li>
                    <a href="<?php echo $this->getFilteredUrl(array($this->getAttributeToFilter() => null)); ?>">
                        <?php echo $this->__('View all'); ?>
                    </a>
                </li>
            <?php endif; ?>
        </ul>
    </div>
</div>

