<?php
/**
 * Blackbird ContentManager Module
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to contact@bird.eu so we can send you a copy immediately.
 *
 * @category	Blackbird
 * @package		Blackbird_ContentManager
 * @copyright	Copyright (c) 2014 Blackbird Content Manager (http://black.bird.eu)
 * @author		Blackbird Team
 * @license		http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @version		1.6.2
 */
?>
<?php
    $_identifier = $this->getIdentifier();
    $_content = $this->getContent();
    
    $_categoryCollection = $this->getCategoryCollection(array('name'));
?>
<?php if($_categoryCollection->getSize()): ?>
<ul class="ct-category-list" id="ct-category-list-<?php echo $this->getIdentifier(); ?>">
    <?php foreach($_categoryCollection as $_category): ?>
        <li class="item">
            <?php $_categoryNameStripped = $this->stripTags($_category->getName(), null, true); ?>
            <p class="category-name"><a href="<?php echo $_category->getUrl() ?>" title="<?php echo $_categoryNameStripped; ?>"><?php echo $_category->getName(); ?></a></p>
        </li>
    <?php endforeach; ?>
</ul>
<script type="text/javascript">
    decorateList($('ct-category-list-<?php echo $this->getIdentifier(); ?>'));
</script>
<?php endif; ?>
