<?php
/**
 * Created by PhpStorm.
 * User: joshcarter
 * Date: 31/05/2016
 * Time: 15:36
 */

class Webtise_Gallery_Model_Resource_Setup extends Mage_Catalog_Model_Resource_Setup
{
    public function getDefaultEntities()
    {
        $entities = array();
        $entities['gallery_gallery'] = array(
            'entity_model'                  => 'gallery/gallery',
            'attribute_model'               => 'gallery/resource_eav_attribute',
            'table'                         => 'gallery/gallery',
            'additional_attribute_table'    => 'gallery/eav_attribute',
            'entity_attribute_collection'   => 'gallery/gallery_attribute_collection',
            'attributes'        => array(
                'status' => array(
                    'group'                     => 'General',
                    'type'                      => 'int',
                    'backend'                   => '',
                    'frontend'                  => '',
                    'label'                     => 'Enabled',
                    'input'                     => 'select',
                    'source'                    => 'eav/entity_attribute_source_boolean',
                    'global'                    => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
                    'required'                  => '1',
                    'user_defined'              => false,
                    'default'                   => '',
                    'unique'                    => false,
                    'position'                  => '10',
                    'note'                      => '',
                    'visible'                   => '1',
                    'wysiwyg_enabled'           => '0',
                ),
                'title' => array(
                    'group'                     => 'General',
                    'type'                      => 'varchar',
                    'backend'                   => '',
                    'frontend'                  => '',
                    'label'                     => 'Title',
                    'input'                     => 'text',
                    'source'                    => '',
                    'global'                    => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
                    'required'                  => '1',
                    'user_defined'              => false,
                    'default'                   => '',
                    'unique'                    => false,
                    'position'                  => '20',
                    'note'                      => '',
                    'visible'                   => '1',
                    'wysiwyg_enabled'           => '0',
                ),
                'description' => array(
                    'group'                     => 'General',
                    'type'                      => 'varchar',
                    'backend'                   => '',
                    'frontend'                  => '',
                    'label'                     => 'Description',
                    'input'                     => 'text',
                    'source'                    => '',
                    'global'                    => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
                    'required'                  => false,
                    'user_defined'              => false,
                    'default'                   => '',
                    'unique'                    => false,
                    'position'                  => '20',
                    'note'                      => 'Shown on the frontend below title before gallery images (optional).',
                    'visible'                   => '1',
                    'wysiwyg_enabled'           => '0',
                ),
                'pages' => array(
                    'group'                     => 'General',
                    'type'                      => 'varchar',
                    'backend'                   => 'eav/entity_attribute_backend_array',
                    'frontend'                  => '',
                    'label'                     => 'Pages to show on',
                    'input'                     => 'multiselect',
                    'source'                    => 'gallery/source_pages',
                    'global'                    => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
                    'required'                  => '1',
                    'user_defined'              => false,
                    'default'                   => '',
                    'unique'                    => false,
                    'position'                  => '30',
                    'note'                      => 'Which pages would you like to show the gallery on?',
                    'visible'                   => '1',
                    'wysiwyg_enabled'           => '0',
                ),
                'display_type' => array(
                    'group'                     => 'General',
                    'type'                      => 'varchar',
                    'backend'                   => 'eav/entity_attribute_backend_array',
                    'frontend'                  => '',
                    'label'                     => 'Display type',
                    'input'                     => 'select',
                    'source'                    => 'gallery/source_display_types',
                    'global'                    => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
                    'required'                  => '1',
                    'user_defined'              => false,
                    'default'                   => '',
                    'unique'                    => false,
                    'position'                  => '40',
                    'note'                      => 'How do you want the Gallery to display? (Not applicable on custom pages when using your own template)',
                    'visible'                   => '1',
                    'wysiwyg_enabled'           => '0',
                ),
                'carousel_items' => array(
                    'group'                     => 'General',
                    'type'                      => 'varchar',
                    'backend'                   => '',
                    'frontend'                  => '',
                    'label'                     => 'Images visible on carousel?',
                    'input'                     => 'text',
                    'source'                    => '',
                    'global'                    => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
                    'required'                  => '1',
                    'user_defined'              => false,
                    'default'                   => '1',
                    'unique'                    => false,
                    'position'                  => '50',
                    'note'                      => 'How many items do you want to be visible on the carousel?',
                    'visible'                   => '1',
                    'wysiwyg_enabled'           => '0',
                ),
                'block_reference' => array(
                    'group'                     => 'General',
                    'type'                      => 'varchar',
                    'backend'                   => 'eav/entity_attribute_backend_array',
                    'frontend'                  => '',
                    'label'                     => 'Block Reference',
                    'input'                     => 'select',
                    'source'                    => 'gallery/source_block_reference',
                    'global'                    => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
                    'required'                  => '1',
                    'user_defined'              => false,
                    'default'                   => '',
                    'unique'                    => false,
                    'position'                  => '60',
                    'note'                      => 'Where abouts on the page would you like the Gallery to be? (Not applicable on custom pages when using your own template)',
                    'visible'                   => '1',
                    'wysiwyg_enabled'           => '0',
                ),
                'image'              => array(
                    'type'                       => 'varchar',
                    'label'                      => 'Base Image',
                    'input'                      => 'media_image',
                    'frontend'                   => 'gallery/gallery_attribute_frontend_image',
                    'required'                   => false,
                    'user_defined'               => false,
                    'sort_order'                 => 1,
                    'visible'                    => '1',
                    'global'                     => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
                    'group'                      => 'Images',
                ),
                'thumbnail'          => array(
                    'type'                       => 'varchar',
                    'label'                      => 'Thumbnail',
                    'input'                      => 'media_image',
                    'frontend'                   => 'gallery/gallery_attribute_frontend_image',
                    'required'                   => false,
                    'sort_order'                 => 3,
                    'global'                     => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
                    'used_in_product_listing'    => true,
                    'group'                      => 'Images',
                ),
                'media_gallery' => array(
                    'type'                      => 'varchar',
                    'label'                     => 'Media Gallery',
                    'input'                     => 'gallery',
                    'backend'                   => 'gallery/gallery_attribute_backend_media',
                    'required'                  => false,
                    'sort_order'                => 4,
                    'group'                     => 'Gallery Images',
                ),
            )
        );
        return $entities;
    }
}