<?php

/* @var $this Epicor_Quickorderpad_Block_Form_Wrapper */
$csvUpload = Mage::getStoreConfigFlag('Epicor_Comm/basket_csv_upload/enabled_quickorderpad');

$listHelper = Mage::helper('epicor_lists/frontend');
/* @var $listHelper Epicor_Lists_Helper_Frontend */

?>
<div class="quickorderpad">
    <?php if (!$this->getHideTitle()) : ?>
    <div class="page-title">
        <h1><?php echo $this->getTitle() ?></h1>
    </div>
    <?php endif; ?>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <div class="qop-search<?php if($csvUpload) : ?> csvincluded<?php endif; ?>">
        <?php echo $this->getChildHtml('search'); ?>
        <?php if($csvUpload) : ?>
            <?php echo $this->getChildHtml('csvupload'); ?>
        <?php endif; ?>
    </div>
    <div class="qop-productlist<?php if(Mage::getStoreConfigFlag('quickorderpad/general/show_cart_summary')) : ?> thinner<?php endif;?>" >
        <?php if(Mage::registry('search-query') != '' || $this->getRequest()->getParam('csv') || ($listHelper->listsEnabled() && $listHelper->getSessionList())) :
                echo $this->getChildHtml('search.result');
              else: ?>
                <div class="page-title">
                    <h1><?php echo $this->__('Enter a search Keyword / SKU') ?></h1>
                </div>
        <?php endif; ?>
    </div>
    <?php if(Mage::getStoreConfigFlag('quickorderpad/general/show_cart_summary')) : ?>
        <div class="qop-summary">
            <?php echo $this->getChildHtml('cart.sidebar'); ?>
        </div>
        <div class="qop-clear"></div>
    <?php endif; ?>
    <?php 
        echo $this->getChildHtml('basket');
        /*
        $showImages = Mage::getStoreConfigFlag('quickorderpad/general/show_quickorderpad_images');
        if($showImages){ 
        <script type="text/javascript" language="javascript">
            //jQuery(".image").show();
            $$('.qop-list .image').invoke(
                    'setStyle', {
                        display: 'table-cell'
            });
        </script>
        }
        */
    ?>
</div>
<script>
    jQuery(".addtobasketform").submit(function(e){
        e.preventDefault();
        var max_quantity = parseInt(jQuery(this).find("input[name='max_quantity']").val());
        var order_qty = parseInt(jQuery(this).find("input[name='qty']").val());
        var product_id = parseInt(jQuery(this).find("input[name='product']").val());
        if (order_qty == 0 ) {
            return false;
        }
        jQuery(".addtobasketform .validation-advice").remove();
        if (false && order_qty > max_quantity) {
            jQuery(this).append('<div class="validation-advice" style="white-space: normal;word-wrap: break-word;">Sorry but your order quantity exceeds the available maximum quantity of # UOM. Please contact our Customer services team on +44 (0) 1772 651199 for further assistance.</div>'.replace('#', max_quantity));
            return false;
        } else {
            var self = this;
            jQuery.ajax({
                type: "GET",
                url: '/retailer/ajax/addBasket',
                data: {'product': product_id, 'qty': order_qty},
                dataType: 'json',
                beforeSend: function () {
                },
                error: function (e) {
                },
                success: function (data) {
                    if (data.status == 'Success') {
                        setLocation('/checkout/cart/');
                    } else if (data.status == 'login') {
                        window.location.href=data.url;
                    } else if (data.status == 'Failed') {
                        jQuery(self).append('<div class="validation-advice" style="white-space: normal;word-wrap: break-word;">' + data.error+ '</div>');
                    } else {
                        console.log('wrong');
                    }
                },
                complete: function () {
                }
            });
        }
    });
</script>
