<?php
/**
 * Blackbird ContentManager Module
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to contact@bird.eu so we can send you a copy immediately.
 *
 * @category	Blackbird
 * @package		Blackbird_ContentManager
 * @copyright	Copyright (c) 2014 Blackbird Content Manager (http://black.bird.eu)
 * @author		Blackbird Team
 * @license		http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @version		1.6.2
 */
?>
<?php
    $collection = $this->getCollection();
    $helper = Mage::helper('contentmanager');
    if($collection && $collection->getSize() > 0):
?>
    <div class="contenttype-results-filter block">
        <div class="block-title"><strong><span><?php echo $this->__('Content Filter'); ?></span></strong></div>
        <div class="current-search">
            <div class="block-content block-ct-filter-content">
                <form method="GET" action="">
                    <input class="input-text" type="text" name="q" value="<?php echo Mage::app()->getRequest()->getParam('q'); ?>" />
                    <button type="submit" class="button"><span><span><?php echo $this->__('OK'); ?></span></span></button>
                </form>
            </div>
        </div>
        <div class="block-content block-ct-filter-content">
            <ul id="contenttype-results-filter-list">
                <?php foreach($collection as $contentType): ?>
                    <li class="<?php echo $this->isOptionActive($contentType->getIdentifier())?'item-active':''; ?>">
                        <a href="<?php echo $this->getFilteredUrl(array('ct' => $contentType->getIdentifier())); ?>">
                            <?php echo $contentType->getTitle(); ?> (<?php echo $this->getTotalByCtId($contentType->getId()); ?>)
                        </a>
                    </li>
                <?php endforeach; ?>
            </ul>
            <script type="text/javascript">decorateList('contenttype-results-filter-list');</script>
        </div>
    </div>
<?php endif; ?>