<?php
$helper = $this->helper('epicor_comm');
/* @var $helper Epicor_Comm_Helper_Data */
$showPrices = $helper->isFunctionalityDisabledForCustomer('prices') ? false : true;
$showUom = Mage::getStoreConfigFlag('Epicor_Comm/units_of_measure/display_in_checkout');
$showInColumn = Mage::getStoreConfigFlag('Epicor_Comm/units_of_measure/display_in_checkout_column');
$contractHelper = Mage::helper('epicor_lists/frontend_contract');
/* @var $contractHelper Epicor_Lists_Helper_Frontend_Contract */
$listEnabled = $contractHelper->contractsEnabled();
$quote = Mage::getSingleton('checkout/session')->getQuote();
$quoteContractCode = $quote->getEccContractCode();
?>
<?php if(Mage::getSingleton('customer/session')->isLoggedIn() && Mage::helper('epicor_comm')->getErpAccountInfo()->getAccountType() == 'B2B'): ?>
<?php echo $this->getChildHtml('items_before'); ?>
 <?php if(($listEnabled) && ($quoteContractCode)): ?>
    <p class="contract-code-order"><?php echo $this->__('<br><b>Contract Code</b>: %s', $contractHelper->getContractTitle($quoteContractCode)); ?></p>
 <?php endif; ?>
<div id="checkout-review-table-wrapper">
    <table class="data-table" id="checkout-review-table">
        <?php if ($this->helper('tax')->displayCartBothPrices()): $colspan = $rowspan = 2; else: $colspan = $rowspan = 1; endif; ?>
        <col />
        <?php if($showUom && $showInColumn) :?>
        <col width="1" />
        <?php endif; ?>
        <?php if ($this->getShowLocations() && $this->getShowLocationsColumn()) : ?>
        <col width="1" />
        <?php endif; ?>
        <?php if ($listEnabled) : ?>
        <col width="1" />
        <?php endif; ?>          
        <?php if ($showPrices) : ?>
        <col width="1" />
        <?php endif; ?>
        <col width="1" />
        <?php if ($showPrices) : ?>
        <col width="1" />
        <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
        <col width="1" />
        <col width="1" />
        <?php endif; ?>
        <?php endif; ?>
        <thead>
            <tr>
                <th rowspan="<?php echo $rowspan ?>"><?php echo $this->__('Product Name') ?></th>
                <?php if($showUom && $showInColumn) :?>
                <th rowspan="<?php echo $rowspan; ?>"><?php echo $this->__('Unit of Measure') ?></th>
                <?php endif; ?>
                <?php if ($this->getShowLocations() && $this->getShowLocationsColumn()) : ?>
                <th rowspan="<?php echo $rowspan; ?>"><?php echo $this->__('Location') ?></th>
                <?php endif; ?>
                <?php if ($listEnabled) : ?>
                <th rowspan="<?php echo $rowspan; ?>"><?php echo $this->__('Contract') ?></th>
                <?php endif; ?>                  
                <?php if ($showPrices) : ?>
                <th colspan="<?php echo $colspan ?>" class="a-center"><?php echo $this->__('Price') ?></th>
                <?php endif; ?>
                <th rowspan="<?php echo $rowspan ?>" class="a-center"><?php echo $this->__('Qty') ?></th>
                <?php if ($showPrices) : ?>
                <th colspan="<?php echo $colspan ?>" class="a-center"><?php echo $this->__('Subtotal') ?></th>
                <?php endif; ?>
            </tr>
            <?php if ($showPrices) : ?>
            <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                <tr>
                    <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                    <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                    <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                    <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                </tr>
            <?php endif; ?>
            <?php endif; ?>
        </thead>
        <?php echo $this->getChildHtml('totals'); ?>
        <tbody>
        <?php foreach($this->getItems() as $_item): ?>
            <?php echo $this->getItemHtml($_item)?>
        <?php endforeach ?>
        </tbody>
    </table>
</div>
<?php echo $this->getChildHtml('items_after'); ?>
<script type="text/javascript">
//<![CDATA[
    decorateTable('checkout-review-table');
    truncateOptions();
//]]>
</script>
<div id="checkout-review-submit">
    <?php echo $this->getChildHtml('agreements') ?>
    <div class="buttons-set" id="review-buttons-container">
        <p class="f-left"><?php echo $this->__('Forgot an Item?') ?> <a href="<?php echo $this->getUrl('checkout/cart') ?>"><?php echo $this->__('Edit Your Cart') ?></a></p>
        <?php echo $this->getChildHtml('button') ?>
        <span class="please-wait" id="review-please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Submitting order information...') ?>" title="<?php echo $this->__('Submitting order information...') ?>" class="v-middle" /> <?php echo $this->__('Submitting order information...') ?>
        </span>
    </div>
    <script type="text/javascript">
    //<![CDATA[
        review = new Review('<?php echo $this->getUrl('checkout/onepage/saveOrder',array('form_key' => Mage::getSingleton('core/session')->getFormKey())) ?>', '<?php echo $this->getUrl('checkout/onepage/success') ?>', $('checkout-agreements'));
    //]]>
    </script>
</div>

<?php else: ?>

<?php echo $this->getChildHtml('items_before'); ?>
 <?php if(($listEnabled) && ($quoteContractCode)): ?>
    <p class="contract-code-order"><?php echo $this->__('<br><b>Contract Code</b>: %s', $contractHelper->getContractTitle($quoteContractCode)); ?></p>
 <?php endif; ?>
<div id="checkout-review-table-wrapper">
    <div class="po-ref">
        <strong>
            <?php if (Mage::getSingleton('checkout/session')->getQuote()->getCustomerOrderRef()) : ?> 
                <?php echo $this->__("Customer Order Reference / Purchase Order Number:"); ?> <?php echo Mage::getSingleton('checkout/session')->getQuote()->getCustomerOrderRef(); ?>
            <?php else: ?>
               <!-- <p>Forget your Customer Order Reference / Purchase Order Number? <a href="#billing" onclick="checkout.changeSection('opc-billing'); return false;">Update</a></p>
	-->
            <?php endif; ?>
        </strong>
    </div>
    <table class="data-table linearize-table" id="checkout-review-table">
        <?php if ($this->helper('tax')->displayCartBothPrices()): $colspan = $rowspan = 2; else: $colspan = $rowspan = 1; endif; ?>
        <col />
        <?php if($showUom && $showInColumn) :?>
        <col width="1" />
        <?php endif; ?>
        <?php if ($this->getShowLocations() && $this->getShowLocationsColumn()) : ?>
        <col width="1" />
        <?php endif; ?>
        <?php if ($listEnabled) : ?>
        <col width="1" />
        <?php endif; ?>
        <?php if ($showPrices) : ?>
        <col width="1" />
        <?php endif; ?>
        <col width="1" />
        <?php if ($showPrices) : ?>
        <col width="1" />
        <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
        <col width="1" />
        <col width="1" />
        <?php endif; ?>
        <?php endif; ?>
        <col width="1" />
        <thead>
            <tr>
                <th rowspan="<?php echo $rowspan ?>"><?php echo $this->__('Product') ?></th>
                <?php if($showUom && $showInColumn) :?>
                <th rowspan="<?php echo $rowspan; ?>"><?php echo $this->__('Unit of Measure') ?></th>
                <?php endif; ?>
                <?php if ($this->getShowLocations() && $this->getShowLocationsColumn()) : ?>
                <th rowspan="<?php echo $rowspan; ?>"><?php echo $this->__('Location') ?></th>
                <?php endif; ?>
                <?php if ($listEnabled) : ?>
                <th rowspan="<?php echo $rowspan; ?>"><?php echo $this->__('Contract') ?></th>
                <?php endif; ?>
                <?php if ($showPrices) : ?>
                <th colspan="<?php echo $colspan ?>" class="a-center"><?php echo $this->__('Price') ?></th>
                <?php endif; ?>
                <th rowspan="<?php echo $rowspan ?>" class="a-center"><?php echo $this->__('Qty') ?></th>
                <?php if ($showPrices) : ?>
                <th colspan="<?php echo $colspan ?>" class="a-center"><?php echo $this->__('Subtotal') ?></th>
                <?php endif; ?>
            </tr>
            <?php if ($showPrices) : ?>
            <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                <tr>
                    <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                    <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                    <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                    <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                </tr>
            <?php endif; ?>
            <?php endif; ?>
        </thead>
        <?php echo $this->getChildHtml('totals'); ?>
        <tbody>
        <?php foreach($this->getItems() as $_item): ?>
            <?php echo $this->getItemHtml($_item)?>
        <?php endforeach ?>
        </tbody>
    </table>
</div>
<?php echo $this->getChildHtml('items_after'); ?>
<script type="text/javascript">
//<![CDATA[
    decorateTable('checkout-review-table');
    truncateOptions();
//]]>
</script>
<div id="checkout-review-submit">
    <?php echo $this->getChildHtml('agreements') ?>
    <div class="buttons-set" id="review-buttons-container">
        <?php echo $this->getChildHtml('button') ?>
        <span class="please-wait" id="review-please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Submitting order information...') ?>" title="<?php echo $this->__('Submitting order information...') ?>" class="v-middle" /> <?php echo $this->__('Submitting order information...') ?>
        </span>
        <p class="f-left"><?php echo $this->__('Forgot an Item?') ?> <a href="<?php echo $this->getUrl('checkout/cart') ?>" onclick="return confirm('<?php echo $this->__('Are you sure you want to leave this page? You will need to go through the checkout steps again.'); ?>')"><?php echo $this->__('Edit Your Cart') ?></a></p>
    </div>
    <script type="text/javascript">
    //<![CDATA[
        review = new SilkCheckoutReview('<?php echo $this->getUrl('checkout/onepage/saveOrder', array('form_key' => Mage::getSingleton('core/session')->getFormKey())) ?>', '<?php echo $this->getUrl('checkout/onepage/success') ?>', $('checkout-agreements'));
    //]]>
    </script>
</div>
<?php endif; ?>
