<?php
/* @var $this Epicor_Comm_Block_Checkout_Cart_Item_Comment */
?>
<?php if ($this->isCommentAllowed() && Mage::getSingleton('customer/session')->isLoggedIn() && Mage::helper('epicor_comm')->getErpAccountInfo()->getAccountType()=='B2B') : ?>
    <fieldset>
        <label for="line_comment_<?php echo $this->getItem()->getId() ?>"><?php echo Mage::helper('epicor_comm')->__('Line Comment') ?></label>
        <div class="input-box">
            <textarea name="cart[<?php echo $this->getItem()->getId() ?>][ecc_line_comment]" class="line_comment" id="line_comment_<?php echo $this->getItem()->getId() ?>"><?php echo $this->getItem()->getEccLineComment() ?></textarea>
        </div>
        <?php if ($this->getRequest()->getControllerName() == 'onepage'):?>
        <div class="field">
            <label for="silk_delivery_date_<?php echo $this->getItem()->getId() ?>" ><?php echo $this->__('Required Date') ?></label>
            <?php
                $silkDeliveryDate = ($this->getItem()->getSilkDeliveryDate() != "0000-00-00") ? $this->getItem()->getSilkDeliveryDate() : null;
                $helperSilkDeliveryDate = Mage::getModel('core/date')->date('d-m-Y', strtotime($silkDeliveryDate . " +0 Weekday"));
            ?>
            <input type="text" class="silk_delivery_date" name="cart[<?php echo $this->getItem()->getId() ?>][silk_delivery_date]" id="silk_delivery_date_<?php echo $this->getItem()->getId() ?>" value="<?php echo $helperSilkDeliveryDate; ?>" title="<?php echo $this->__('Select Required Date'); ?> " readonly="readonly"/>
            <img class="status_help" title="Select date" id="required_date_trig_<?php echo $this->getItem()->getId() ?>" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . 'adminhtml/default/default/images/grid-cal.gif'; ?>"  class="v-middle" />
            <script type="text/javascript">
                 Calendar.setup({
//                    onSelect: function(cal) { cal.hide() },
                    showTime: false,
                    button:"required_date_trig_<?php echo $this->getItem()->getId() ?>",
                    align : "Bl",
                    inputField:"silk_delivery_date_<?php echo $this->getItem()->getId();?>",
                    ifFormat : "%d-%m-%Y",
                     singleClick: true,
                     disableFunc: function (date) {
                        var now = new Date();
                        //var now = new Date("<?php echo Mage::getModel('core/date')->date('d-m-Y', strtotime($silkDeliveryDate));?>");
                        if (date.getFullYear() < now.getFullYear()) {

                            return true;
                        }
                        if (date.getFullYear() == now.getFullYear()) {
                            if (date.getMonth() < now.getMonth()) {
                                return true;
                            }
                        }
                        if (date.getMonth() == now.getMonth()) {
                            if (date.getDate() <= now.getDate()) {
                                return true;
                            }
                        }
                        if (date.getDay() == 6 || date.getDay()==0) {
                            return true;
                        }
                    },
                });
                //        cal.manageFields("required_date_trig_<?php //echo $this->getItem()->getId() ?>//", "silk_delivery_date_<?php //echo $this->getItem()->getId();?>//", "%d-%m-%Y");
            </script>
        </div>
        <?php endif; ?>
    </fieldset>
    <?php if ($this->getCommentLimit() > 0): ?>
        <script>
            jQuery(function () {
                jQuery('#line_comment_<?php echo $this->getItem()->getId() ?>').maxlength({
                    maxCharacters: <?php echo $this->getCommentLimit(); ?>, // Characters limit
                    statusClass: "max-len-feedback", // The class on the status div
                    statusText: "<?php echo Mage::helper('epicor_comm')->__('Chars Remaining'); ?>", // The status text
                });
            })
        </script>
    <?php endif; ?>
    <?php if ($this->getRequest()->getControllerName() == 'onepage'):?>

    <?php endif;?>
<?php endif; ?>
