<?php
/**
 * Template for block Webtise_Gallery_Block_Adminhtml_Gallery_Helper_Gallery_Content
 */
?>
<?php
$_block = $this;
?>
<div id="<?php echo $_block->getHtmlId() ?>" >
    <div class="grid">
        <table cellspacing="0" class="data border" id="<?php echo $_block->getHtmlId() ?>_grid" width="100%">
            <col width="1" />
            <col width="500" />
            <col width="500" />
            <col width="500" />
            <col width="500" />
            <col width="70" />
            <col width="70" />
            <col width="70" />
            <thead>
            <tr class="headings">
                <th><?php echo Mage::helper('gallery')->__('Image') ?></th>
                <th><?php echo Mage::helper('gallery')->__('Label') ?></th>
                <th><?php echo Mage::helper('gallery')->__('Related Product Ids (comma separated)') ?></th>
                <th><?php echo Mage::helper('gallery')->__('Image Specific Url') ?></th>
                <th><?php echo Mage::helper('gallery')->__('Image Tag Ids (comma separated)') ?></th>
                <th><?php echo Mage::helper('gallery')->__('Sort Order') ?></th>
                <th><?php echo Mage::helper('gallery')->__('Exclude') ?></th>
                <th class="last"><?php echo Mage::helper('gallery')->__('Remove') ?></th>
            </tr>
            </thead>
            <tbody id="<?php echo $_block->getHtmlId() ?>_list">
            <tr id="<?php echo $_block->getHtmlId() ?>_template" class="template no-display">
                <td class="cell-image"><div class="place-holder" onmouseover="<?php echo $_block->getJsObjectName(); ?>.loadImage('__file__')"><span><?php echo Mage::helper('gallery')->__('Roll Over for preview') ?></span></div><img src="<?php echo $this->getSkinUrl('images/spacer.gif')?>" width="100" style="display:none;" alt="" /></td>
                <td class="cell-label"><input type="text" <?php if($_block->getElement()->getReadonly()):?> disabled="disabled"<?php endif;?> class="input-text" onkeyup="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" onchange="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" /></td>
                <td class="cell-related-product-ids"><input type="text" <?php if($_block->getElement()->getReadonly()):?> disabled="disabled"<?php endif;?> class="input-text" onkeyup="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" onchange="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" /></td>
                <td class="cell-image-specific-url"><input type="text" <?php if($_block->getElement()->getReadonly()):?> disabled="disabled"<?php endif;?> class="input-text" onkeyup="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" onchange="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" /></td>
                <td class="cell-image-tag-ids"><input type="text" <?php if($_block->getElement()->getReadonly()):?> disabled="disabled"<?php endif;?> class="input-text" onkeyup="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" onchange="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" /></td>
                <td class="cell-position"><input type="text" <?php if($_block->getElement()->getReadonly()):?> disabled="disabled"<?php endif;?> class="input-text validate-number" onkeyup="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" onchange="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" /></td>
                <td class="cell-disable a-center"><input type="checkbox" <?php if($_block->getElement()->getReadonly()):?> disabled="disabled"<?php endif;?> onclick="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" /></td>
                <td class="cell-remove a-center last"><input type="checkbox" <?php if($_block->getElement()->getReadonly()):?> disabled="disabled"<?php endif;?> onclick="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" /></td>
            </tr>
            <tr id="<?php echo $_block->getHtmlId() ?>-image-0">
                <td class="cell-image"><?php echo Mage::helper('gallery')->__('No image') ?></td>
                <td class="cell-label"><input type="hidden" />&nbsp;</td>
                <td class="cell-related-product-ids"><input type="hidden" />&nbsp;</td>
                <td class="cell-image-specific-url"><input type="hidden" />&nbsp;</td>
                <td class="cell-image-tag-ids"><input type="hidden" />&nbsp;</td>
                <td class="cell-position"><input type="hidden" />&nbsp;</td>
                <td class="cell-disable"><input type="hidden" />&nbsp;</td>
                <td class="cell-remove last"><input type="hidden" />&nbsp;</td>
            </tr>
            </tbody>
            <?php if (!$_block->getElement()->getReadonly()):?>
                <tfoot>
                <tr>
                    <td colspan="100" class="last" style="padding:8px">
                        <?php echo $_block->getUploaderHtml() ?>
                    </td>
                </tr>
                </tfoot>
            <?php endif;?>
        </table>
    </div>
</div>
<input type="hidden" id="<?php echo $_block->getHtmlId() ?>_save" name="<?php echo $_block->getElement()->getName() ?>[images]" value="<?php echo $_block->escapeHtml($_block->getImagesJson()) ?>" />
<input type="hidden" id="<?php echo $_block->getHtmlId() ?>_save_image" name="<?php echo $_block->getElement()->getName() ?>[values]" value="<?php echo $_block->escapeHtml($_block->getImagesValuesJson()) ?>" />
<script type="text/javascript">
    //<![CDATA[
    var <?php echo $_block->getJsObjectName(); ?> = new Gallery.Gallery('<?php echo $_block->getHtmlId() ?>');
    //]]>
</script>