<?php
    /** @var Interjar_CollectionsCategory_Block_Category_View $this */
    $_category = $this->getCurrentCategory();
    $_subcategories = $this->getSubcategoryCollection();
    $updateUrl = Mage::helper('collectionscategory')->getProductsUpdateUrl();
?>
<?php if ($_subcategories): ?>
    <div class="subcategories-wrapper">
        <?php foreach ($_subcategories as $subcategory): ?>
            <?php $_products = $this->getProductsFromCategory($subcategory); ?>
            <?php if ($_products): ?>
                <div class="subcategory">
                    <h3 class="subcategory-title"><?php echo $this->__($subcategory->getName()); ?></h3>
                    <div class="subcategory-products <?php echo $subcategory->getId().'-subcategorySlider'; ?>" id="<?php echo $subcategory->getId().'-subcategorySlider' ?>">
                        <?php /** @var Interjar_CollectionsCategory_Block_Category_Subcategory_Product $subcategoryProductBlock */ ?>
                        <?php echo $this->getSubcategoryProductBlock($subcategory, $_products); ?>
                    </div>
                </div>
            <?php endif; ?>

        

        <?php endforeach; ?>
    </div>
<?php endif; ?>
