<?php if(Mage::getSingleton('customer/session')->isLoggedIn() && Mage::helper('epicor_comm')->getErpAccountInfo()->getAccountType() == 'B2B'): ?>
<div class="page-title">
    <h1><?php echo $this->__('Checkout') ?></h1>
</div>
<script type="text/javascript" src="<?php echo $this->getJsUrl('varien/accordion.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/opcheckout.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getJsUrl('onepage/shipping_dates.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('epicor/comm/js/line-comments.js') ?>"></script>

<ol class="opc" id="checkoutSteps">
<?php $i=0; foreach($this->getSteps() as $_stepId => $_stepInfo): ?>
<?php if (!$this->getChild($_stepId) || !$this->getChild($_stepId)->isShow()): continue; endif; $i++ ?>
    <li id="opc-<?php echo $_stepId ?>" class="section<?php echo !empty($_stepInfo['allow'])?' allow':'' ?><?php echo !empty($_stepInfo['complete'])?' saved':'' ?>">
        <div class="step-title">
            <span class="number"><?php echo $i ?></span>
            <h2><?php echo $_stepInfo['label'] ?></h2>
            <a href="#"><?php echo $this->__('Edit') ?></a>
        </div>
        <div id="checkout-step-<?php echo $_stepId ?>" class="step a-item" style="display:none;">
            <?php echo $this->getChildHtml($_stepId) ?>
        </div>
    </li>
<?php endforeach ?>
</ol>
<script type="text/javascript">
//<![CDATA[
    var accordion = new Accordion('checkoutSteps', '.step-title', true);
    <?php if($this->getActiveStep()): ?>
    accordion.openSection('opc-<?php echo $this->getActiveStep() ?>');
    <?php endif ?>
    var checkout = new ShippingDates(accordion,{
        progress: '<?php echo $this->getUrl('checkout/onepage/progress') ?>',
        review: '<?php echo $this->getUrl('checkout/onepage/review') ?>',
        saveMethod: '<?php echo $this->getUrl('checkout/onepage/saveMethod') ?>',
        failure: '<?php echo $this->getUrl('checkout/cart') ?>'}
    );
//]]>
</script>
<?php 
$helper = Mage::helper('epicor_lists/frontend_restricted');
/* @var $helper Epicor_Lists_Helper_Frontend_Restricted */
$ajaxDeliveryAddressUrl = Mage::getUrl('epicor_lists/list/changeshippingaddress', $helper->issecure());
$checkoutUrl = Mage::getUrl('epicor_lists/list/changebillingaddressajax', $helper->issecure());
$checkoutUrlShipping = Mage::getUrl('epicor_lists/list/changeshippingaddressajax', $helper->issecure());
$cartPopupurl = Mage::getUrl('epicor_lists/list/cartpopup', $helper->issecure());
$selectAddress = Mage::getUrl('epicor_lists/list/selectaddressajax', $helper->issecure());
?>
<input type="hidden" name="ajaxdeliveryaddressurl" id="ajaxdeliveryaddressurl" value="<?php echo $ajaxDeliveryAddressUrl; ?>">
<input type="hidden" name="deliverycartpopupurl" id="deliverycartpopupurl" value="<?php echo $cartPopupurl; ?>">
<input type="hidden" name="selectaddress" id="selectaddress" value="<?php echo $selectAddress; ?>">
<input type="hidden" name="changebillingaddressajax" id="changebillingaddressajax" value="<?php echo $checkoutUrl; ?>">
<input type="hidden" name="changeshippingaddressajax" id="changeshippingaddressajax" value="<?php echo $checkoutUrlShipping; ?>">

<?php else: ?>

<div class="page-title">
    <h1><?php echo $this->__('Checkout') ?></h1>
</div>
<script type="text/javascript" src="<?php echo $this->getJsUrl('varien/accordion.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/opcheckout.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/opcheckout_rwd.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getJsUrl('onepage/shipping_dates.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('epicor/comm/js/line-comments.js') ?>"></script>
<!-- New Code Added Below  -->
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/removecheckout.js') ?>"></script>
<ol class="opc opc-firststep-<?php echo $this->getActiveStep() ?>" id="checkoutSteps">
<?php $i=0; foreach($this->getSteps() as $_stepId => $_stepInfo): ?>
<?php if (!$this->getChild($_stepId) || !$this->getChild($_stepId)->isShow()): continue; endif; $i++ ?>
    <li id="opc-<?php echo $_stepId ?>" class="section<?php echo !empty($_stepInfo['allow'])?' allow':'' ?><?php echo !empty($_stepInfo['complete'])?' saved':'' ?>">
        <div class="step-title">
            <span class="number"><?php echo $i ?></span>
            <?php /* <h2><?php echo $_stepInfo['label'] ?></h2> */ ?>
	<h2><?php if($_stepId=='billing'): echo 'Ship to Address';?>
		<?php elseif($_stepId =='shipping'): echo 'Confirm Address'; ?>
		<?php else: echo $_stepInfo['label']; endif;?>
	</h2>
           <h2><?php //echo $_stepId == 'shipping' ? 'Ship To Information' : $_stepInfo['label'] ?></h2>
            <a href="#"><?php echo $this->__('Edit') ?></a>
        </div>
        <div id="checkout-step-<?php echo $_stepId ?>" class="step a-item" style="display:none;">
            <?php echo $this->getChildHtml($_stepId) ?>
        </div>
    </li>
<?php endforeach ?>
</ol>
<script type="text/javascript">
//<![CDATA[
    var accordion = new Accordion('checkoutSteps', '.step-title', true);
    <?php if($this->getActiveStep()): ?>
    accordion.openSection('opc-<?php echo $this->getActiveStep() ?>');
    <?php endif ?>
    //Modified code to remove steps:
    var checkout = new SilkCheckout(accordion,{
        progress: '<?php echo $this->getUrl('checkout/onepage/progress') ?>',
        review: '<?php echo $this->getUrl('checkout/onepage/review') ?>',
        saveMethod: '<?php echo $this->getUrl('checkout/onepage/saveMethod') ?>',
        failure: '<?php echo $this->getUrl('checkout/cart') ?>'}
    );
    //billing.save();
//]]>
</script>
<?php
$helper = Mage::helper('epicor_lists/frontend_restricted');
/* @var $helper Epicor_Lists_Helper_Frontend_Restricted */
$ajaxDeliveryAddressUrl = Mage::getUrl('epicor_lists/list/changeshippingaddress', $helper->issecure());
$checkoutUrl = Mage::getUrl('epicor_lists/list/changebillingaddressajax', $helper->issecure());
$checkoutUrlShipping = Mage::getUrl('epicor_lists/list/changeshippingaddressajax', $helper->issecure());
$cartPopupurl = Mage::getUrl('epicor_lists/list/cartpopup', $helper->issecure());
$selectAddress = Mage::getUrl('epicor_lists/list/selectaddressajax', $helper->issecure());
?>
<input type="hidden" name="ajaxdeliveryaddressurl" id="ajaxdeliveryaddressurl" value="<?php echo $ajaxDeliveryAddressUrl; ?>">
<input type="hidden" name="deliverycartpopupurl" id="deliverycartpopupurl" value="<?php echo $cartPopupurl; ?>">
<input type="hidden" name="selectaddress" id="selectaddress" value="<?php echo $selectAddress; ?>">
<input type="hidden" name="changebillingaddressajax" id="changebillingaddressajax" value="<?php echo $checkoutUrl; ?>">
<input type="hidden" name="changeshippingaddressajax" id="changeshippingaddressajax" value="<?php echo $checkoutUrlShipping; ?>">

<?php endif; ?>
