<?php
/**
 * Blackbird ContentManager Module
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to contact@bird.eu so we can send you a copy immediately.
 *
 * @category	Blackbird
 * @package		Blackbird_ContentManager
 * @copyright	Copyright (c) 2014 Blackbird Content Manager (http://black.bird.eu)
 * @author		Blackbird Team
 * @license		http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @version		1.6.2
 */
?>
<?php
$_element = $this->getElement();
$_note    = $_element->getNote();
$_trId    = $_element->getHtmlContainerId();
$_class   = $_element->getFieldsetHtmlClass();

$option = Mage::helper('contentmanager')->getOptionByFieldIdentifier($_element->getName(), $this->getRequest()->getParam('id'));
?>
<?php if (!$_element->getNoDisplay()): ?>
<tr<?php if($_trId): ?> id="<?php echo $_trId ?>"<?php endif; ?>>
    <?php if ($_element->getType()=='hidden'): ?>
    <td colspan="2" class="hidden"><?php echo trim($_element->getElementHtml()) ?></td>
    <?php else: ?>
    <td class="label<?php echo $_class ? " {$_class}-label" : ''?>"><?php echo trim($_element->getLabelHtml()) ?></td>
    <td class="<?php echo $_element->hasValueClass() ? $_element->getValueClass() : 'value' ?><?php echo $_class ? " {$_class}-value" : ''?>">
        <?php
           $action = 'getProductChooser(\'' . $this->getUrl('adminhtml/cm_ajax_widget/chooser', array('attribute' => 'category', 'form' => 'rule_conditions_fieldset', '_secure' => Mage::app()->getStore()->isAdminUrlSecure())) . '?isAjax=true\', \''.$_element->getHtmlId().'\'); return false;';
        ?>
        <input id="<?php echo $_element->getHtmlId() ?>" name="<?php echo $_element->getName() ?>" value="<?php echo $_element->getEscapedValue() ?>" <?php echo $_element->serialize($_element->getHtmlAttributes()) ?> />

        <a href="javascript:void(0)" class="rule-choose-trigger" onclick="<?php echo $action; ?>"><img src="<?php echo Mage::getDesign()->getSkinUrl('images/rule_chooser_trigger.gif'); ?>" alt="" class="v-middle" title="<?php echo Mage::helper('contentmanager')->__('Open Chooser'); ?>" /></a>
        <a href="javascript:void(0)" class="rule-param-apply" onclick="$('chooser-container-<?php echo $_element->getName() ?>').innerHTML = '';"><img src="<?php echo Mage::getDesign()->getSkinUrl('images/rule_component_apply.gif'); ?>" class="v-middle" alt="<?php echo Mage::helper('contentmanager')->__('Apply'); ?>" title="<?php echo Mage::helper('contentmanager')->__('Apply'); ?>"></a>
        
        <div class="chooser-container" id="chooser-container-<?php echo $_element->getName() ?>"></div>
        
        <?php echo $this->getAfterElementHtml() ?>
        
        <?php if ($_note): ?>
            <p class="note<?php echo $_class ? " {$_class}-note" : ''?>" id="note_<?php echo $_element->getId()?>"><span><?php echo $_note ?></span></p>
        <?php endif ?>
    </td>
    <?php endif; ?>
</tr>
<?php endif; ?>
