<?php
/**
 * Blackbird ContentManager Module
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to contact@bird.eu so we can send you a copy immediately.
 *
 * @category	Blackbird
 * @package		Blackbird_ContentManager
 * @copyright	Copyright (c) 2014 Blackbird Content Manager (http://black.bird.eu)
 * @author		Blackbird Team
 * @license		http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @version		1.6.2
 */
?>
<script type="text/javascript">

OptionTemplateFile = '<table class="border" cellpadding="0" cellspacing="0" style="width: 900px">'+
        '<tr class="headings">'+
            '<th class="type-title">' + <?php echo $this->helper('core')->jsonEncode(Mage::helper('catalog')->__('Allowed File Extensions')); ?> + '</th>'+
            '<th class="">' + <?php echo $this->helper('core')->jsonEncode(Mage::helper('catalog')->__('File path')); ?> + '</th>' +
            '<th class="imageonly">' + <?php echo $this->helper('core')->jsonEncode(Mage::helper('catalog')->__('Enable crop')); ?> + '</th>' +
            '<th class="imageonly" style="display: none;">' + <?php echo $this->helper('core')->jsonEncode(Mage::helper('catalog')->__('Resolution to crop the image onto')); ?> + '</th>' +
            '<th class="imageonly" style="display: none;">' + <?php echo $this->helper('core')->jsonEncode(Mage::helper('catalog')->__('Keep aspect ratio')); ?> + '</th>' +
            '<th class="imageonly" style="display: none;">' + <?php echo $this->helper('core')->jsonEncode(Mage::helper('catalog')->__('Alt extra field')); ?> + '</th>' +
            '<th class="imageonly" style="display: none;">' + <?php echo $this->helper('core')->jsonEncode(Mage::helper('catalog')->__('URL extra field')); ?> + '</th>' +
            '<th class="imageonly last" style="display: none;">' + <?php echo $this->helper('core')->jsonEncode(Mage::helper('catalog')->__('Title extra field')); ?> + '</th>' +
        '</tr>' +
        '<tr>' +
            '<td><input class="input-text file_extensions" type="text" name="contenttype[options][{{option_id}}][file_extension]" value="{{file_extension}}"><br/><p class="note"><?php echo $this->__('Comma separated list'); ?></p></td>' +
            '<td><input class="input-text" type="text" name="contenttype[options][{{option_id}}][file_path]" value="{{file_path}}"><br/><p class="note"><?php echo $this->__('Sub-directly to store files. e.g.: documents/'); ?></p></td>' +
            '<td class="imageonly"><input type="checkbox" id="crop_{{option_id}}" name="contenttype[options][{{option_id}}][crop]" value="1"><br/><p class="note"><?php echo $this->__('Add a crop tool'); ?></p></td>' +
            '<td class="imageonly" style="display: none;">'+
                '<input class="input-text" type="text" style="width: 60px !important;" name="contenttype[options][{{option_id}}][crop_w]" value="{{crop_w}}"> x '+
                '<input class="input-text" style="width: 60px !important;" type="text" name="contenttype[options][{{option_id}}][crop_h]" value="{{crop_h}}"><br/><p class="note"><?php echo $this->__('The output resolution of the cropped image, expressed as WIDTHxHEIGHT (e.g. 640x480). Set to 0 not to rescale after cropping.'); ?></p>'+
            '</td>'+
            '<td class="imageonly" style="display: none;"><input type="checkbox" id="keep_aspect_ratio_{{option_id}}" name="contenttype[options][{{option_id}}][keep_aspect_ratio]" value="1"><br/><p class="note"><?php echo $this->__('Check this to force the ratio of the output on the crop box. NOTE: If you leave this unchecked but enforce an output resolution, the final image might be distorted.'); ?></p></td>' +
            '<td class="imageonly" style="display: none;"><input type="checkbox" id="img_alt_{{option_id}}" name="contenttype[options][{{option_id}}][img_alt]" value="1"></td>' +
            '<td class="imageonly" style="display: none;"><input type="checkbox" id="img_url_{{option_id}}" name="contenttype[options][{{option_id}}][img_url]" value="1"></td>' +
            '<td class="imageonly" style="display: none;"><input type="checkbox" id="img_title_{{option_id}}" name="contenttype[options][{{option_id}}][img_title]" value="1"></td>' +
        '</tr>'+
    '</table>';

if ($('option_panel_type_file')) {
    $('option_panel_type_file').remove();
}

</script>
