<?php
/**
 * Blackbird ContentManager Module
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to contact@bird.eu so we can send you a copy immediately.
 *
 * @category	Blackbird
 * @package		Blackbird_ContentManager
 * @copyright	Copyright (c) 2014 Blackbird Content Manager (http://black.bird.eu)
 * @author		Blackbird Team
 * @license		http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @version		1.6.2
 */
?>
<script type="text/javascript">
//<![CDATA[

/**
 * @todo Resolve
 */
var nothing = '<table class="border" cellpadding="0" cellspacing="0">'+
        '<tr class="headings">'+
            '<th width="50" class=""><?php echo Mage::helper('catalog')->__('Products SKU') ?> </th>'+
        '</tr>'+
        '<tr>'+
            '<td class="value">'+
            '<input type="text" class="input-text entities" name="widget_instance[{{id}}][<?php echo (isset($container['name']))?$container['name']:'' ?>][entities]" value="{{<?php echo (isset($container['name']))?$container['name']:'' ?>_entities}}" readonly="readonly" />&nbsp;' +
            '<a class="widget-option-chooser" href="javascript:void(0)" onclick="WidgetInstance.displayEntityChooser(\'sku\', \'products_ids_{{id}}\')"  title="<?php echo $this->helper('core')->jsQuoteEscape(Mage::helper('widget')->__('Open Chooser')) ?>">' +
            '<img src="<?php echo Mage::getDesign()->getSkinUrl('images/rule_chooser_trigger.gif') ?>" class="v-middle" alt="<?php echo $this->helper('core')->jsQuoteEscape(Mage::helper('widget')->__('Open Chooser')); ?>" />' +
            '</a>'+
            '</td>'+
            /*'<td class="value"><input type="text" class="input-text" name="contenttype[options][{{option_id}}][default_value]" value="{{default_value}}"></td>'+*/
        '</tr>'+
    '</table>';

//]]>
</script>


<?php
    $contentTypes = '<option value="0">'.$this->__('All content types').'</option>';
    $collection = Mage::getModel('contentmanager/contenttype')->getCollection()->addFieldToSelect(array('identifier', 'title'));
    foreach($collection as $contentType)
    {
        $contentTypes .= '<option value="'.$contentType->getIdentifier().'">'.addslashes($contentType->getTitle()).'</option>';
    }
    
    $attributes = '';
    $collection = Mage::getResourceModel('catalog/product_attribute_collection')->getItems();
    
    foreach($collection as $attribute)
    {
        if($attribute->getFrontendInput() == 'select' || $attribute->getFrontendInput() == 'multiselect')
        {
            $attributes .= '<option value="'.$attribute->getAttributeCode().'">'.$attribute->getAttributeCode().' ('.addslashes($attribute->getFrontendLabel()).')</option>';
        }
    }
?>
<script type="text/javascript">

OptionTemplateRelation = '<table class="border contentonly" cellpadding="0" cellspacing="0" style="width: 900px">'+
        '<tr class="headings">'+
            '<th class="type-title">' + <?php echo $this->helper('core')->jsonEncode(Mage::helper('catalog')->__('Content Type')); ?> + '</th>'+
        '</tr>' +
        '<tr>' +
            '<td><select class="select" id="content_type_{{option_id}}" name="contenttype[options][{{option_id}}][content_type]"><?php echo $contentTypes; ?></select><br/><p class="note"><?php echo $this->__('Limit the choice for this content type'); ?></p></td>' +
        '</tr>'+
    '</table><table class="border attributeonly" cellpadding="0" cellspacing="0" style="width: 900px">'+
        '<tr class="headings">'+
            '<th class="type-title">' + <?php echo $this->helper('core')->jsonEncode(Mage::helper('contentmanager')->__('Attribute')); ?> + '</th>'+
            '<th class="type-title">' + <?php echo $this->helper('core')->jsonEncode(Mage::helper('contentmanager')->__('Multi-select')); ?> + '</th>'+
        '</tr>' +
        '<tr>' +
            '<td><select class="select" id="attribute_product_{{option_id}}" name="contenttype[options][{{option_id}}][attribute]"><?php echo $attributes; ?></select><br/><p class="note"><?php echo $this->__('Limit the choice for this attribute options'); ?></p></td>' +
            '<td><select class="select" id="attribute_limit_{{option_id}}" name="contenttype[options][{{option_id}}][max_characters]"><option value="0"><?php echo Mage::helper('contentmanager')->__('No'); ?></option><option value="1"><?php echo Mage::helper('contentmanager')->__('Yes'); ?></option></select></td>' +
        '</tr>'+
    '</table>';

if ($('option_panel_type_relation')) {
    $('option_panel_type_relation').remove();
}

</script>
